//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1_Client.SayHello {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SayHello.ISayHello")]
    public interface ISayHello {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISayHello/DoWork", ReplyAction="http://tempuri.org/ISayHello/DoWorkResponse")]
        string DoWork(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISayHello/DoWork", ReplyAction="http://tempuri.org/ISayHello/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISayHello/OpeningJobs", ReplyAction="http://tempuri.org/ISayHello/OpeningJobsResponse")]
        System.Collections.Generic.Dictionary<string, int> OpeningJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISayHello/OpeningJobs", ReplyAction="http://tempuri.org/ISayHello/OpeningJobsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> OpeningJobsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISayHello/OpeningJobsByRole", ReplyAction="http://tempuri.org/ISayHello/OpeningJobsByRoleResponse")]
        int OpeningJobsByRole(string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISayHello/OpeningJobsByRole", ReplyAction="http://tempuri.org/ISayHello/OpeningJobsByRoleResponse")]
        System.Threading.Tasks.Task<int> OpeningJobsByRoleAsync(string role);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISayHelloChannel : Assignment1_Client.SayHello.ISayHello, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SayHelloClient : System.ServiceModel.ClientBase<Assignment1_Client.SayHello.ISayHello>, Assignment1_Client.SayHello.ISayHello {
        
        public SayHelloClient() {
        }
        
        public SayHelloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SayHelloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SayHelloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SayHelloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork(string name) {
            return base.Channel.DoWork(name);
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync(string name) {
            return base.Channel.DoWorkAsync(name);
        }
        
        public System.Collections.Generic.Dictionary<string, int> OpeningJobs() {
            return base.Channel.OpeningJobs();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> OpeningJobsAsync() {
            return base.Channel.OpeningJobsAsync();
        }
        
        public int OpeningJobsByRole(string role) {
            return base.Channel.OpeningJobsByRole(role);
        }
        
        public System.Threading.Tasks.Task<int> OpeningJobsByRoleAsync(string role) {
            return base.Channel.OpeningJobsByRoleAsync(role);
        }
    }
}
